#!/bin/sh
### A short script that controls the website.
if [ "$1" = "update" ]; then
    python3 satg.py
    rsync -vrP --delete-after ./build/ root@prestonpan.tech:/var/www/prestonpan
elif [ "$1" = "build" ]; then
    python3 satg.py
elif [ "$1" = "clean" ]; then
    rm -rf build/
elif [ "$1" = "view" ]; then
    abrowser build/index.html
elif [ "$1" = "add" ]; then
    python3 make_content.py
else
    python3 satg.py
    rsync -vrP --delete-after ./build/ root@prestonpan.tech:/var/www/prestonpan
fi
